### ISSUE TITLE
Add option to direct init holder variables

### ISSUE THREAD

**Issue by x7airworker** [DisabledMallis/ClassBuilder#2]
When working with functions a signature scanner is used, which gets lazy called through the first call.
This is a good solution for just calling the functions, but it would be quite nice to have to option to direct init, to use the holder for e.g. hooking

**Comment by DisabledMallis** [comment]
Yeah this is something ive been thinking about and personally I havent been able to come up with a good approach yet. If you look at https://github.com/DisabledMallis/Nuvola you'd see my hooks/patches are totally seperate. Being able to expose the addresses to hook and such directly from classes or really in any neater fashion would be nice, but I just dont know a good way I can do this. If you have suggestions or ideas, please tell me and I'll consider.

**Comment by DisabledMallis** [comment]
Adding to this, directly being able to initialize breaks the idea of classbuilder by creating new functions in classes that dont normally exist. The idea of class builder is to generate code to expose existing code and classes, so this might be outside of the scope of ClassBuilder

**Comment by x7airworker** [comment]
> Yeah this is something ive been thinking about and personally I havent been able to come up with a good approach yet. If you look at https://github.com/DisabledMallis/Nuvola you'd see my hooks/patches are totally seperate. Being able to expose the addresses to hook and such directly from classes or really in any neater fashion would be nice, but I just dont know a good way I can do this. If you have suggestions or ideas, please tell me and I'll consider.

I've been thinking of two options to do this:

- Generate an extra function and directly call, like `static inline uintptr_t holder_init = Mem::InitHolder("CA FE BA BE")`
- There is https://github.com/eyalroz/cpp-static-block which just works like the java static block, but in C++ might be cleaner but even more dependencies are needed

**Comment by x7airworker** [comment]
> Adding to this, directly being able to initialize breaks the idea of classbuilder by creating new functions in classes that dont normally exist. The idea of class builder is to generate code to expose existing code and classes, so this might be outside of the scope of ClassBuilder

I agree that this may be out of scope, but double pasting the same signatures also isn't a good solution.

**Comment by DisabledMallis** [comment]
> > Yeah this is something ive been thinking about and personally I havent been able to come up with a good approach yet. If you look at https://github.com/DisabledMallis/Nuvola you'd see my hooks/patches are totally seperate. Being able to expose the addresses to hook and such directly from classes or really in any neater fashion would be nice, but I just dont know a good way I can do this. If you have suggestions or ideas, please tell me and I'll consider.
> 
> I've been thinking of two options to do this:
> 
> - Generate an extra function and directly call, like `static inline uintptr_t holder_init = Mem::InitHolder("CA FE BA BE")`
> - There is https://github.com/eyalroz/cpp-static-block which just works like the java static block, but in C++ might be cleaner but even more dependencies are needed
> 

Might implement this approach

**Comment by x7airworker** [comment]
Which approach exactly? I would do a Pull Request then

**Comment by DisabledMallis** [comment]
> Which approach exactly? I would do a Pull Request then

The `static inline uintptr_t holder_init = Mem::InitHolder("CA FE BA BE")` one

**Comment by DisabledMallis** [comment]
Implemented on #4
