### ISSUE TITLE
Generate Macro calls instead of direct calls

### ISSUE THREAD

**Issue by x7airworker** [DisabledMallis/ClassBuilder#5]
So the generation should be changed to macros:

- `Utils::PreInit` -> `CLASSBUILDER_PREINIT`
- `Mem::FindSig` -> `CLASSBUILDER_FINDSIG`
- `Utils::DebugF` -> `CLASSBUILDER_DEBUG`

This will allow to `#define` those to fit your needs

**Comment by DisabledMallis** [comment]
I knew I wanted to implement a way to configure external funcs and such, but this is such a brilliant and simple solution I can't believe I didn't think of! If you want to PR it, let me know now, otherwise I'll start working on an implementation.

**Comment by x7airworker** [comment]
Don't have time to do it rn, so you can implement it.

**Comment by DisabledMallis** [comment]
will do

**Comment by DisabledMallis** [comment]
Added on main branch
